spring:
  application:
    name: mopo
  datasource:
    url: jdbc:mysql://localhost:3306/mopo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.bit.mopo.model
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-dir: uploads/